#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ruijie Switch Configuration Collector
======================================
通过锐捷交换机 Web 管理接口批量采集运行配置。
Batch-collect running-configs from Ruijie switches via their web management API.

Algorithm note
--------------
The auth token is generated by the front-end JavaScript in ``base.dao.js`` /
``login.js`` using ``getPasswordEncode()``:

    pa = "aFhTRUpVVmxWYVYxWlZN"
    for i in range(5):
        password = base64.encode(password)   # standard Base64
        password = pa + password             # prepend the fixed prefix

Starting value is ``"<username>:<password>"``.

Author  : 360NENZ  <https://github.com/360NENZ>
License : MIT
"""

from __future__ import annotations

import argparse
import base64
import ipaddress
import json
import logging
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from xml.etree import ElementTree as ET

import requests
import urllib3
import yaml

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

LOG_FORMAT = "%(asctime)s [%(levelname)-8s] %(message)s"
logging.basicConfig(format=LOG_FORMAT, datefmt="%Y-%m-%d %H:%M:%S", level=logging.INFO)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants — derived directly from base.dao.js / login.js
# ---------------------------------------------------------------------------

#: Fixed prefix prepended in each encoding round (``pa`` variable in source JS)
_AUTH_PREFIX: str = "aFhTRUpVVmxWYVYxWlZN"

#: Number of encode rounds (``for(i=0;i<5;i++)`` in getPasswordEncode)
_AUTH_ROUNDS: int = 5


# ===========================================================================
# Auth helpers  (mirrors getPasswordEncode in base.dao.js / login.js)
# ===========================================================================

def generate_auth_token(username: str, password: str) -> str:
    """
    Encode ``username:password`` using Ruijie's ``getPasswordEncode()`` scheme.

    JavaScript source (``base.dao.js`` and ``login.js``)::

        getPasswordEncode: function(password) {
            pa = "aFhTRUpVVmxWYVYxWlZN";
            for (i = 0; i < 5; i++) {
                password = base64.encode(password);
                password = pa + password;
            }
            return password;
        }

    Each of the 5 rounds: standard Base64-encode the current string, then
    prepend the fixed prefix ``_AUTH_PREFIX``.
    The initial value is ``"<username>:<password>"``.

    Parameters
    ----------
    username : str
    password : str

    Returns
    -------
    str  – value for the ``auth`` POST field of ``/login.do``
    """
    token: str = f"{username}:{password}"
    for _ in range(_AUTH_ROUNDS):
        token = base64.b64encode(token.encode("utf-8")).decode("ascii")
        token = _AUTH_PREFIX + token
    return token


def decode_auth_token(token: str) -> tuple[str, str] | None:
    """
    Reverse a Ruijie auth token back to ``(username, password)``.

    Strips the known prefix and Base64-decodes in reverse for ``_AUTH_ROUNDS``
    iterations.  Returns ``None`` when the format does not match.
    """
    current = token
    for _ in range(_AUTH_ROUNDS):
        if not current.startswith(_AUTH_PREFIX):
            return None
        current = current[len(_AUTH_PREFIX):]
        try:
            current = base64.b64decode(current.encode("ascii")).decode("utf-8")
        except Exception:
            return None
    if ":" in current:
        user, _, pwd = current.partition(":")
        return user, pwd
    return None


# ===========================================================================
# Switch client
# ===========================================================================

class RuijieSwitch:
    """
    HTTP client for a single Ruijie switch.

    Workflow
    --------
    1. ``login()``        – POST to ``/login.do``, acquire session cookie
    2. ``web_cli(cmd)``   – POST to ``/web_cli.do``, parse XML response
    3. ``collect()``      – convenience wrapper that chains the above
    """

    _BASE_HEADERS: dict[str, str] = {
        "Accept":           "text/plain, */*; q=0.01",
        "Accept-Language":  "zh-CN,zh;q=0.9,en;q=0.8",
        "Connection":       "keep-alive",
        "Content-Type":     "application/x-www-form-urlencoded",
        "X-Requested-With": "XMLHttpRequest",
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        ),
    }

    def __init__(
        self,
        ip: str,
        auth_token: str,
        *,
        timeout: int = 10,
        verify_ssl: bool = False,
    ) -> None:
        self.ip = ip
        self.auth_token = auth_token
        self.timeout = timeout
        self.base_url = f"http://{ip}"

        self.session = requests.Session()
        self.session.verify = verify_ssl
        self.session.cookies.set("LOCAL_LANG_COOKIE", "zh")
        self.session.cookies.set("UI_LOCAL_COOKIE",   "zh")

    # ------------------------------------------------------------------
    # Login
    # ------------------------------------------------------------------

    def login(self) -> bool:
        """
        POST credentials to ``/login.do``.

        Returns ``True`` when the server sets a valid ``SID`` cookie,
        which indicates a successful authentication.
        """
        url = f"{self.base_url}/login.do"
        headers = {
            **self._BASE_HEADERS,
            "Origin":  self.base_url,
            "Referer": f"{self.base_url}/index.htm",
        }
        try:
            self.session.post(
                url,
                headers=headers,
                data={"auth": self.auth_token},
                timeout=self.timeout,
                allow_redirects=True,
            )
        except requests.exceptions.ConnectionError:
            logger.debug("[%s] Connection refused or host unreachable", self.ip)
            return False
        except requests.exceptions.Timeout:
            logger.debug("[%s] Connection timed out", self.ip)
            return False
        except Exception as exc:  # noqa: BLE001
            logger.debug("[%s] Login error: %s", self.ip, exc)
            return False

        cookies = self.session.cookies.get_dict()
        sid = cookies.get("SID", "deleted")

        if sid and sid != "deleted":
            logger.debug("[%s] Login OK  SID=%s", self.ip, sid)
            # Inject Web-CLI navigation cookies that the browser JS normally sets
            self.session.cookies.set("module",      "system")
            self.session.cookies.set("subModule",   "console")
            self.session.cookies.set("threeModule", "console_setting")
            return True

        logger.debug("[%s] Login failed. cookies=%s", self.ip, cookies)
        return False

    # ------------------------------------------------------------------
    # Web CLI
    # ------------------------------------------------------------------

    def web_cli(self, command: str) -> dict | None:
        """
        Execute *command* via the Web CLI endpoint ``/web_cli.do``.

        Returns a dict with keys ``mode_tip``, ``content``, ``return_code``,
        or ``None`` on any error.
        """
        url = f"{self.base_url}/web_cli.do"
        headers = {
            **self._BASE_HEADERS,
            "Origin":  self.base_url,
            "Referer": f"{self.base_url}/common/webcli.htm",
        }
        data = {
            "command":      command,
            "mode_url":     "exec",
            "mode_intidx":  "0",
            "mode_intidx1": "0",
            "mode_intidx2": "0",
            "mode_prompt":  "",
            "mode_stridx":  "",
        }
        try:
            resp = self.session.post(
                url,
                headers=headers,
                data=data,
                timeout=self.timeout,
            )
        except Exception as exc:  # noqa: BLE001
            logger.debug("[%s] web_cli error: %s", self.ip, exc)
            return None

        if resp.status_code != 200:
            logger.debug("[%s] web_cli HTTP %d", self.ip, resp.status_code)
            return None

        return self._parse_xml(resp.text)

    @staticmethod
    def _parse_xml(xml_text: str) -> dict | None:
        """
        Parse the ``<webcli-print>`` XML envelope returned by ``/web_cli.do``.

        Key fields:

        * ``<mode-tip>``    – ``<HOSTNAME>#``  (e.g. ``DXL-5007#``)
        * ``<content>``     – command output text
        * ``<return-code>`` – ``0`` = success
        """
        try:
            root = ET.fromstring(xml_text)
        except ET.ParseError as exc:
            logger.debug("XML parse error: %s", exc)
            return None

        def _text(tag: str) -> str:
            el = root.find(tag)
            return (el.text or "").strip() if el is not None else ""

        return {
            "mode_tip":    _text("mode-tip"),
            "content":     _text("content"),
            "return_code": _text("return-code"),
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _hostname_from_tip(mode_tip: str) -> str | None:
        """
        Extract the hostname from a ``<mode-tip>`` value.

        Examples
        --------
        ``DXL-5007#``   →  ``DXL-5007``
        ``Switch>``     →  ``Switch``
        ``CORE-SW-01#`` →  ``CORE-SW-01``
        """
        m = re.match(r"^(.+?)\s*[#>]\s*$", mode_tip)
        return m.group(1).strip() if m else None

    def get_running_config(self) -> tuple[str | None, str | None]:
        """
        Execute ``show running-config`` and return ``(hostname, config_text)``.

        Both values are ``None`` when the command fails or yields no output.
        """
        data = self.web_cli("show running-config")
        if not data:
            return None, None

        hostname = self._hostname_from_tip(data.get("mode_tip", ""))

        # Fallback: parse ``hostname <name>`` from the config body itself
        if not hostname:
            m = re.search(
                r"^hostname\s+(\S+)", data.get("content", ""), re.MULTILINE
            )
            hostname = m.group(1) if m else None

        content = data.get("content") or None
        return hostname, content

    # ------------------------------------------------------------------
    # Collect
    # ------------------------------------------------------------------

    def collect(self) -> dict:
        """
        Full collection workflow for this device.

        Returns
        -------
        dict with keys: ``ip``, ``hostname``, ``config``, ``success``, ``error``
        """
        result: dict = {
            "ip":       self.ip,
            "hostname": None,
            "config":   None,
            "success":  False,
            "error":    None,
        }

        if not self.login():
            result["error"] = "Login failed"
            return result

        hostname, config = self.get_running_config()

        if not hostname:
            result["error"] = "Could not determine hostname"
            return result

        if not config:
            result["error"] = "Running-config is empty"
            return result

        result["hostname"] = hostname
        result["config"]   = config
        result["success"]  = True
        return result


# ===========================================================================
# Config loading
# ===========================================================================

def load_config(path: str) -> dict:
    """Load and validate ``config.yml``."""
    p = Path(path)
    if not p.exists():
        logger.error("Config file not found: %s", path)
        sys.exit(1)

    with p.open(encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)

    if not isinstance(cfg, dict):
        logger.error("config.yml is empty or invalid")
        sys.exit(1)

    auth      = cfg.get("auth", {})
    has_token = bool(auth.get("token"))
    has_creds = bool(auth.get("username")) and bool(auth.get("password"))

    if not has_token and not has_creds:
        logger.error(
            "config.yml must define either 'auth.token' or "
            "both 'auth.username' and 'auth.password'"
        )
        sys.exit(1)

    return cfg


def resolve_auth_token(auth: dict) -> str:
    """Return the auth token, generating it from credentials when needed."""
    if auth.get("token"):
        return auth["token"]
    token = generate_auth_token(auth["username"], auth["password"])
    logger.debug("Generated auth token for user '%s'", auth["username"])
    return token


# ===========================================================================
# IP target expansion
# ===========================================================================

def expand_targets(targets: dict) -> list[str]:
    """
    Expand the *targets* section of config.yml into a sorted list of IPs.

    Supported formats
    -----------------
    ``ips``     – explicit IP strings
    ``subnets`` – CIDR notation  (e.g. ``192.168.1.0/24``)
    ``ranges``  – dash notation  (e.g. ``192.168.1.1-254``)
    """
    ips: set[str] = set()

    for raw in targets.get("ips", []):
        try:
            ipaddress.ip_address(raw)
            ips.add(raw)
        except ValueError:
            logger.warning("Skipping invalid IP: %s", raw)

    for cidr in targets.get("subnets", []):
        try:
            net   = ipaddress.ip_network(cidr, strict=False)
            hosts = list(net.hosts())
            for h in hosts:
                ips.add(str(h))
            logger.info("Subnet %s → %d host addresses", cidr, len(hosts))
        except ValueError:
            logger.warning("Skipping invalid subnet: %s", cidr)

    for rng in targets.get("ranges", []):
        m = re.match(r"^(\d+\.\d+\.\d+)\.(\d+)-(\d+)$", rng.strip())
        if not m:
            logger.warning("Skipping invalid range: %s", rng)
            continue
        prefix, start, end = m.group(1), int(m.group(2)), int(m.group(3))
        for i in range(start, end + 1):
            ips.add(f"{prefix}.{i}")
        logger.info("Range %s → %d addresses", rng, end - start + 1)

    return sorted(ips, key=lambda x: ipaddress.ip_address(x))


# ===========================================================================
# Output helpers
# ===========================================================================

def _safe_filename(hostname: str) -> str:
    """Strip characters that are illegal in filenames."""
    return re.sub(r'[<>:"/\\|?*\x00-\x1f]', "_", hostname)


def save_config(hostname: str, ip: str, config: str, configs_dir: Path) -> Path:
    """
    Write the running-config to ``configs/<Hostname>_<IP>.text``.

    Returns the path of the written file.
    """
    configs_dir.mkdir(parents=True, exist_ok=True)
    path = configs_dir / f"{_safe_filename(hostname)}_{ip}.text"
    path.write_text(config, encoding="utf-8")
    logger.info("[%s] Config saved  → %s", ip, path)
    return path


def update_maps(
    hostname: str,
    ip: str,
    maps_path: Path,
    lock: threading.Lock,
) -> None:
    """
    Thread-safe upsert of one entry into ``maps.json``.

    ``maps.json`` stores a JSON object keyed by IP address::

        {
          "172.31.99.83": {
            "hostname":     "DXL-5007",
            "ip":           "172.31.99.83",
            "collected_at": "2026-03-17T10:30:00"
          }
        }

    All successful devices from every run are accumulated in this single file,
    so re-runs update existing entries rather than creating new files.
    """
    entry = {
        "hostname":     hostname,
        "ip":           ip,
        "collected_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }
    with lock:
        maps: dict = {}
        if maps_path.exists():
            try:
                maps = json.loads(maps_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                maps = {}
        maps[ip] = entry
        maps_path.write_text(
            json.dumps(maps, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    logger.info("[%s] maps.json updated (hostname=%s)", ip, hostname)


# ===========================================================================
# Per-switch worker
# ===========================================================================

def process_switch(
    ip: str,
    auth_token: str,
    request_cfg: dict,
    output_dir: Path,
    maps_path: Path,
    maps_lock: threading.Lock,
) -> dict:
    """Login, collect data, persist files, and return a result dict."""
    timeout    = int(request_cfg.get("timeout",    10))
    verify_ssl = bool(request_cfg.get("verify_ssl", False))

    switch = RuijieSwitch(ip, auth_token, timeout=timeout, verify_ssl=verify_ssl)
    result = switch.collect()

    if result["success"]:
        configs_dir = output_dir / "configs"
        config_path = save_config(
            result["hostname"], ip, result["config"], configs_dir
        )
        update_maps(result["hostname"], ip, maps_path, maps_lock)
        result["config_path"] = str(config_path)
        logger.info("[%s] ✓  Hostname: %s", ip, result["hostname"])
    else:
        logger.warning("[%s] ✗  %s", ip, result["error"])

    return result


# ===========================================================================
# CLI entry-point
# ===========================================================================

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="ruijie-collector",
        description=(
            "Batch-collect running-configs from Ruijie switches "
            "via the built-in web management API."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py                        # use config.yml in current directory
  python main.py -c /etc/switches.yml   # custom config path
  python main.py -o /data/backups       # custom output directory
  python main.py --dry-run              # list targets without connecting
  python main.py -v                     # verbose / debug output
  python main.py --decode-token TOKEN   # decode a Ruijie auth token
        """,
    )
    p.add_argument(
        "-c", "--config",
        default="config.yml",
        metavar="FILE",
        help="Path to YAML configuration file (default: config.yml)",
    )
    p.add_argument(
        "-o", "--output",
        default=".",
        metavar="DIR",
        help="Output directory (default: current directory)",
    )
    p.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable DEBUG-level logging",
    )
    p.add_argument(
        "--dry-run",
        action="store_true",
        help="Print target IPs and exit without connecting",
    )
    p.add_argument(
        "--decode-token",
        metavar="TOKEN",
        help="Decode a Ruijie auth token and print the plaintext credentials",
    )
    return p


def main() -> None:
    args = build_parser().parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # ── Utility: decode a token ──────────────────────────────────────────
    if args.decode_token:
        creds = decode_auth_token(args.decode_token)
        if creds:
            print(f"Username : {creds[0]}")
            print(f"Password : {creds[1]}")
        else:
            print("Could not decode token (prefix mismatch or corrupted data).")
        return

    # ── Load config ───────────────────────────────────────────────────────
    cfg         = load_config(args.config)
    auth_token  = resolve_auth_token(cfg.get("auth", {}))
    targets_cfg = cfg.get("targets", {})
    request_cfg = cfg.get("request", {})

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    ips = expand_targets(targets_cfg)
    if not ips:
        logger.error(
            "No valid target IPs found. "
            "Check the 'targets' section in config.yml."
        )
        sys.exit(1)

    logger.info("Targets: %d IP(s)", len(ips))

    if args.dry_run:
        print(f"\nDry-run — {len(ips)} target(s):")
        for ip in ips:
            print(f"  {ip}")
        print()
        return

    # ── Shared state for maps.json ────────────────────────────────────────
    maps_path = output_dir / "maps.json"
    maps_lock = threading.Lock()

    # ── Concurrent collection ─────────────────────────────────────────────
    max_workers = int(request_cfg.get("concurrent", 5))
    results: list[dict] = []

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        future_map = {
            pool.submit(
                process_switch,
                ip,
                auth_token,
                request_cfg,
                output_dir,
                maps_path,
                maps_lock,
            ): ip
            for ip in ips
        }
        for future in as_completed(future_map):
            ip = future_map[future]
            try:
                results.append(future.result())
            except Exception as exc:  # noqa: BLE001
                logger.error("[%s] Unhandled exception: %s", ip, exc)
                results.append({"ip": ip, "success": False, "error": str(exc)})

    # ── Summary ───────────────────────────────────────────────────────────
    ok   = [r for r in results if r["success"]]
    fail = [r for r in results if not r["success"]]

    bar = "=" * 60
    print(f"\n{bar}")
    print("  Collection Summary")
    print(bar)
    print(f"  Total     : {len(results)}")
    print(f"  Success   : {len(ok)}")
    print(f"  Failed    : {len(fail)}")

    if ok:
        print(f"\n  {'IP Address':<22}  Hostname")
        print(f"  {'-'*22}  {'-'*20}")
        for r in sorted(ok, key=lambda x: ipaddress.ip_address(x["ip"])):
            print(f"  {r['ip']:<22}  {r['hostname']}")

    if fail:
        print(f"\n  {'IP Address':<22}  Error")
        print(f"  {'-'*22}  {'-'*30}")
        for r in sorted(fail, key=lambda x: x["ip"]):
            print(f"  {r['ip']:<22}  {r.get('error', 'unknown')}")

    if ok:
        print(f"\n  Mapping file : {maps_path}")
        print(f"  Configs dir  : {output_dir / 'configs'}")

    print(f"{bar}\n")


if __name__ == "__main__":
    main()
